project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m408_s24
  title: "MATH 408"
  site-url: www.inqs.info/m408_s24
  navbar:
    right:
      - syllabus.qmd
      - books.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true



