---
title: "Class 13"
author: "Isaac Quintanilla Salinas"
date: "`r format(Sys.time(),'%m-%d-%Y')`"
output: 
  html_notebook:
    toc: true
    toc_float: true
    code_folding: hide
---

## Simulation Study 1

```{r}
library(magrittr)
library(tidyverse)
sim1 <- function(i){
  x1 <- rnorm(1000, 2)
  x2 <- rnorm(1000, -4)
  y <- 3 + 2 * x1 + 4 * x2 + rnorm(1000, sd = sqrt(2))
  df <- tibble(x1, x2, y)
  res <- df %$% lm(y ~ x1 + x2)
  return(c(coef(res),sigma(res)))
}
sim2 <- function(i){
  x1 <- rnorm(1000, 2)
  x2 <- rnorm(1000, -4)
  y <- 3 + 2 * x1 + 4 * x2 + rnorm(1000, sd = sqrt(2))
  df <- tibble(x1, x2, y)
  res <- df %$% lm(y ~ x1)
  return(c(coef(res),sigma(res)))
}

# sim1()
print("Correct Model")
print("Average estimate")
results1 <- sapply(1:1000, sim1)
rowMeans(results1)
print("Theoretical Standard Error Estimates")
apply(results1, 1, sd)
print("Incorrect Model")
print("Average estimate")
results2 <- sapply(1:1000, sim2)
rowMeans(results2)
print("Theoretical Standard Error Estimates")
apply(results2, 1, sd)
```

## Simulation Study 2

```{r}
sim3 <- function(i){
  x1 <- rnorm(1000, 8)
  # x2 <- rnorm(1000, -4)
  y <- 3 + 2 * log(x1)  + rnorm(1000, sd = sqrt(2))
  df <- tibble(x1, y)
  res <- df %$% lm(y ~ log(x1))
  return(c(coef(res),sigma(res)))
}
sim4 <- function(i){
  x1 <- rnorm(1000, 8)
  # x2 <- rnorm(1000, -4)
  y <- 3 + 2 * log(x1) + rnorm(1000, sd = sqrt(2))
  df <- tibble(x1, y)
  res <- df %$% lm(y ~ x1)
  return(c(coef(res),sigma(res)))
}


print("Correct Model")
print("Average estimate")
results1 <- sapply(1:1000, sim3)
rowMeans(results1)
print("Theoretical Standard Error Estimates")
apply(results1, 1, sd)
print("Incorrect Model")
print("Average estimate")
results2 <- sapply(1:1000, sim4)
rowMeans(results2)
print("Theoretical Standard Error Estimates")
apply(results2, 1, sd)
```

## Matrix Formulation

```{r}
library(palmerpenguins)
penguins %<>% drop_na
ymat <- penguins$body_mass_g
print("flipper length and bill length")
xmat <- cbind(1, penguins$flipper_length_mm ,penguins$bill_length_mm)
solve(t(xmat)%*%xmat)%*%t(xmat)%*%ymat
print("lm results")
penguins %$% lm(body_mass_g ~ flipper_length_mm + bill_length_mm)

print("flipper length and island")
penguins %<>% mutate(island_torg = relevel(island, ref = "Torgersen"))
xmat <- penguins %$% model.matrix(~flipper_length_mm+island_torg)
solve(t(xmat)%*%xmat)%*%t(xmat)%*%ymat
penguins %$% lm(body_mass_g ~ flipper_length_mm + island_torg)

```
